## 1)	Load in the appropriate csv file as a pandas dataframe (batting.csv)

In [79]:
import pandas as pd
import numpy as np
df=pd.read_csv('batting.csv')

## 2) Print out the dimensions and info about the dataframe you just created

In [80]:
data = pd.DataFrame(df)
data

,playerID,nameFirst,nameLast,birthYear,yearID,stint,teamID,lgID,G,AB,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abercda01,Frank,Abercrombie,1850,1871,1,TRO,NaN,1,4,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
1,addybo01,Bob,Addy,1842,1871,1,RC1,NaN,25,118,...,13.0,8.0,1.0,4,0.0,NaN,NaN,NaN,NaN,NaN
2,allisar01,Art,Allison,1849,1871,1,CL1,NaN,29,137,...,19.0,3.0,1.0,2,5.0,NaN,NaN,NaN,NaN,NaN
3,allisdo01,Doug,Allison,1846,1871,1,WS3,NaN,27,133,...,27.0,1.0,1.0,0,2.0,NaN,NaN,NaN,NaN,NaN
4,ansonca01,Cap,Anson,1852,1871,1,RC1,NaN,25,120,...,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,NaN
5,armstbo01,Robert,Armstrong,1850,1871,1,FW1,NaN,12,49,...,5.0,0.0,1.0,0,1.0,NaN,NaN,NaN,NaN,NaN
6,barkeal01,Al,Barker,1839,1871,1,RC1,NaN,1,4,...,2.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
7,barnero01,Ross,Barnes,1850,1871,1,BS1,NaN,31,157,...,34.0,11.0,6.0,13,1.0,NaN,NaN,NaN,NaN,NaN
8,barrebi01,Bill,Barrett,0,1871,1,FW1,NaN,1,5,...,1.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
9,barrofr01,Frank,Barrows,1844,1871,1,BS1,NaN,18,86,...,11.0,1.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
10,bassjo01,John,Bass,1848,1871,1,CL1,NaN,22,89,...,18.0,0.0,1.0,3,4.0,NaN,NaN,NaN,NaN,NaN
11,battijo01,Joe,Battin,1853,1871,1,CL1,NaN,1,3,...,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
12,bealsto01,Tommy,Beals,1850,1871,1,WS3,NaN,10,36,...,1.0,2.0,0.0,2,0.0,NaN,NaN,NaN,NaN,NaN
13,beaveed01,Edward,Beavens,1848,1871,1,TRO,NaN,3,15,...,5.0,2.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
14,bechtge01,George,Bechtel,1848,1871,1,PH1,NaN,20,94,...,21.0,4.0,0.0,2,2.0,NaN,NaN,NaN,NaN,NaN
15,bellast01,Steve,Bellan,1849,1871,1,TRO,NaN,29,128,...,23.0,4.0,4.0,9,2.0,NaN,NaN,NaN,NaN,NaN
16,berkena01,Nate,Berkenstock,1831,1871,1,PH1,NaN,1,4,...,0.0,0.0,0.0,0,3.0,NaN,NaN,NaN,NaN,NaN
17,berryto01,Tom,Berry,1842,1871,1,PH1,NaN,1,4,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
18,berthha01,Harry,Berthrong,1844,1871,1,WS3,NaN,17,73,...,8.0,3.0,1.0,4,2.0,NaN,NaN,NaN,NaN,NaN
19,biermch01,Charles,Bierman,1845,1871,1,FW1,NaN,1,2,...,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
20,birdge01,George,Bird,1850,1871,1,RC1,NaN,25,106,...,13.0,1.0,0.0,3,2.0,NaN,NaN,NaN,NaN,NaN
21,birdsda01,Dave,Birdsall,1838,1871,1,BS1,NaN,29,152,...,24.0,6.0,0.0,4,4.0,NaN,NaN,NaN,NaN,NaN
22,brainas01,Asa,Brainard,1841,1871,1,WS3,NaN,30,134,...,21.0,4.0,0.0,7,2.0,NaN,NaN,NaN,NaN,NaN
23,brannmi01,Mike,Brannock,1851,1871,1,CH1,NaN,3,14,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
24,burrohe01,Henry,Burroughs,1845,1871,1,WS3,NaN,12,63,...,14.0,0.0,0.0,1,1.0,NaN,NaN,NaN,NaN,NaN
25,careyto01,Tom,Carey,1846,1871,1,FW1,NaN,19,87,...,10.0,5.0,0.0,2,1.0,NaN,NaN,NaN,NaN,NaN
26,carleji01,Jim,Carleton,1848,1871,1,CL1,NaN,29,127,...,18.0,2.0,1.0,8,3.0,NaN,NaN,NaN,NaN,NaN
27,conefr01,Fred,Cone,1848,1871,1,BS1,NaN,19,77,...,16.0,12.0,1.0,8,2.0,NaN,NaN,NaN,NaN,NaN
28,connone01,Ned,Connor,1850,1871,1,TRO,NaN,7,33,...,2.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
29,cravebi01,Bill,Craver,1844,1871,1,TRO,NaN,27,118,...,26.0,6.0,3.0,3,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102786,wittgni01,Nick,Wittgren,1991,2016,1,MIA,NL,48,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102787,wolteto01,Tony,Wolters,1992,2016,1,COL,NL,71,205,...,30.0,4.0,1.0,21,53.0,2.0,0.0,4.0,0.0,1.0
102788,wongko01,Kolten,Wong,1990,2016,1,SLN,NL,121,313,...,23.0,7.0,0.0,34,52.0,2.0,9.0,0.0,5.0,3.0
102789,woodal02,Alex,Wood,1991,2016,1,LAN,NL,15,16,...,2.0,0.0,0.0,1,9.0,0.0,0.0,2.0,0.0,0.0
102790,woodbl01,Blake,Wood,1985,2016,1,CIN,NL,70,2,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102791,woodtr01,Travis,Wood,1987,2016,1,CHN,NL,81,11,...,1.0,0.0,0.0,1,5.0,0.0,0.0,0.0,0.0,0.0
102792,worleva01,Vance,Worley,1987,2016,1,BAL,AL,35,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102793,worthda01,Danny,Worth,1985,2016,1,HOU,AL,16,39,...,1.0,0.0,0.0,1,6.0,0.0,0.0,0.0,0.0,1.0
102794,wrighda03,David,Wright,1982,2016,1,NYN,NL,37,137,...,14.0,3.0,2.0,26,55.0,0.0,0.0,0.0,0.0,0.0
102795,wrighda04,Daniel,Wright,1991,2016,1,CIN,NL,4,5,...,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
102796,wrighda04,Daniel,Wright,1991,2016,2,LAA,AL,5,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102797,wrighmi01,Mike,Wright,1990,2016,1,BAL,AL,18,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102798,wrighst01,Steven,Wright,1984,2016,1,BOS,AL,25,4,...,0.0,0.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0
102799,yateski01,Kirby,Yates,1987,2016,1,NYA,AL,41,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102800,yelicch01,Christian,Yelich,1991,2016,1,MIA,NL,155,578,...,98.0,9.0,4.0,72,138.0,4.0,4.0,0.0,5.0,20.0
102801,ynoaga01,Gabriel,Ynoa,1993,2016,1,NYN,NL,10,3,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102802,ynoami01,Michael,Ynoa,1991,2016,1,CHA,AL,23,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102803,ynoara01,Rafael,Ynoa,1987,2016,1,COL,NL,3,5,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102804,youngch03,Chris,Young,1979,2016,1,KCA,AL,34,1,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102805,youngch04,Chris,Young,1983,2016,1,BOS,AL,76,203,...,24.0,4.0,2.0,21,50.0,0.0,3.0,0.0,0.0,4.0
102806,younger03,Eric,Young,1985,2016,1,NYA,AL,6,1,...,0.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102807,youngma03,Madison,Younginer,1990,2016,1,ATL,NL,8,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102808,zastrro01,Rob,Zastryzny,1992,2016,1,CHN,NL,8,3,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102809,zieglbr01,Brad,Ziegler,1979,2016,1,ARI,NL,36,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102810,zieglbr01,Brad,Ziegler,1979,2016,2,BOS,AL,33,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102811,zimmejo02,Jordan,Zimmermann,1986,2016,1,DET,AL,19,4,...,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
102812,zimmery01,Ryan,Zimmerman,1984,2016,1,WAS,NL,115,427,...,46.0,4.0,1.0,29,104.0,1.0,5.0,0.0,6.0,12.0
102813,zobribe01,Ben,Zobrist,1981,2016,1,CHN,NL,147,523,...,76.0,6.0,4.0,96,82.0,6.0,4.0,4.0,4.0,17.0
102814,zuninmi01,Mike,Zunino,1991,2016,1,SEA,AL,55,164,...,31.0,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0
102815,zychto01,Tony,Zych,1990,2016,1,SEA,AL,12,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

## 3) How many players have hit 40 or more HRs in one single season? (Number only)

In [99]:
df2 = pd.DataFrame(df, columns = ['playerID', 'yearID', 'HR','teamID'])

In [105]:
 q3=df2.groupby(['playerID','yearID']).agg({'HR':'sum'})

In [106]:
HR40 =q3[q3.HR >= 40].sort_values(by = 'HR', ascending = True)

In [7]:
HR40.count() # Indicates number of players who have hit 40 or more HRs in one single season

HR    330
dtype: int64

## 4) How many players have hit more than 600 HRs for their career?

In [74]:
q4 = df.groupby('playerID').sum()

In [75]:
q4

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,...,BB,SO,IBB,HBP,SH,SF,GIDP,PA,Avg,OBP
playerID,,,,,,,,,,,,,,,,,,,,,
aardsda01,17829,18084,9,331,4,0,0,0,0,0,...,0,2.0,0.0,0.0,1.0,0.0,0.0,5.0,0.000000,0.500000
aaronha01,44482,45195,23,3298,12364,2174,3771,624,98,755,...,1402,1383.0,293.0,32.0,21.0,121.0,328.0,13695.0,6.924731,10.029224
aaronto01,13573,13768,7,437,944,102,216,42,6,13,...,86,145.0,3.0,0.0,9.0,6.0,36.0,1048.0,1.544619,2.188188
aasedo01,25402,25786,13,448,5,0,0,0,0,0,...,0,3.0,0.0,0.0,0.0,0.0,0.0,5.0,0.000000,0.000000
abadan01,5916,6010,3,15,21,1,2,0,0,0,...,4,5.0,0.0,0.0,0.0,0.0,1.0,25.0,0.117647,0.901961
abadfe01,15880,16107,9,315,9,0,1,0,0,0,...,0,5.0,0.0,0.0,0.0,0.0,1.0,9.0,0.142857,0.142857
abadijo01,3700,3750,3,12,49,4,11,0,0,0,...,0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,0.472222,NaN
abbated01,18770,19051,11,855,3044,355,772,99,43,11,...,289,16.0,NaN,33.0,93.0,NaN,NaN,NaN,2.278729,NaN
abbeybe01,11214,11365,7,79,225,21,38,3,3,0,...,21,54.0,NaN,0.0,4.0,NaN,NaN,NaN,1.265942,NaN
abbeych01,9330,9475,5,451,1751,307,492,67,46,19,...,167,105.0,NaN,23.0,18.0,NaN,NaN,NaN,1.370584,NaN
abbotda01,1862,1890,1,3,7,0,1,0,1,0,...,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.142857,NaN
abbotfr01,5622,5712,3,160,513,48,107,21,6,1,...,19,NaN,NaN,8.0,20.0,NaN,NaN,NaN,0.599837,NaN
abbotgl01,23412,23743,13,248,0,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
abbotje01,9860,9995,5,233,596,82,157,33,2,18,...,38,91.0,2.0,3.0,5.0,7.0,12.0,648.0,1.236065,1.616251
abbotji01,21637,21932,12,263,21,0,2,0,0,0,...,0,10.0,0.0,0.0,3.0,0.0,1.0,24.0,0.095238,0.238095
abbotku01,19690,19971,11,702,2044,273,523,109,23,62,...,133,571.0,11.0,17.0,21.0,12.0,37.0,2221.0,2.510197,3.288488
abbotky01,7872,7974,4,57,31,2,3,1,0,0,...,1,19.0,0.0,0.0,6.0,0.0,0.0,38.0,0.568966,0.810345
abbotod01,1888,1910,1,22,70,2,13,2,1,0,...,6,20.0,NaN,0.0,6.0,NaN,NaN,NaN,0.185714,NaN
abbotpa01,23604,23977,13,162,20,2,5,1,0,0,...,0,6.0,0.0,0.0,5.0,0.0,0.0,25.0,0.831818,1.554545
aberal01,15416,15635,10,168,100,5,14,0,0,0,...,8,41.0,0.0,0.0,8.0,1.0,2.0,42.0,1.742463,2.026471
abercda01,1850,1871,1,1,4,0,0,0,0,0,...,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
abercre01,5940,6021,3,180,386,65,86,20,2,9,...,21,123.0,2.0,7.0,5.0,2.0,3.0,416.0,0.718224,0.897124
abernbi01,1929,1952,1,1,1,0,0,0,0,0,...,0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.000000,NaN
abernbr01,9885,10014,6,232,868,97,212,36,5,8,...,60,93.0,1.0,7.0,16.0,4.0,15.0,949.0,0.824518,1.280665
abernte01,5763,5829,3,7,5,0,1,0,0,0,...,1,3.0,NaN,0.0,0.0,NaN,0.0,NaN,0.250000,NaN
abernte02,32861,33409,21,681,181,12,25,3,0,0,...,6,74.0,0.0,2.0,15.0,0.0,4.0,202.0,2.919030,4.523889
abernwo01,3830,3893,2,16,8,0,0,0,0,0,...,0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,NaN
aberscl01,5763,5844,3,63,179,25,45,7,3,5,...,25,44.0,NaN,0.0,0.0,NaN,6.0,NaN,0.466071,NaN
ablesha01,5649,5725,3,14,26,0,0,0,0,0,...,0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.000000,NaN
abnersh01,13762,13928,8,392,840,89,191,39,4,11,...,43,153.0,10.0,7.0,5.0,7.0,14.0,905.0,1.550141,2.058060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zimmejo02,15888,16100,8,200,324,18,55,6,0,1,...,10,99.0,0.0,0.0,44.0,2.0,2.0,380.0,1.464058,2.870035
zimmero01,1913,1945,1,27,98,14,27,1,0,5,...,5,16.0,NaN,3.0,0.0,NaN,2.0,NaN,0.275510,NaN
zimmery01,23808,24126,12,1408,5416,793,1505,338,20,215,...,539,1087.0,41.0,25.0,1.0,58.0,173.0,6055.0,3.422829,4.785802
zinkch01,1979,2008,1,1,0,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
zinkwa01,1898,1921,1,2,1,0,0,0,0,0,...,0,1.0,NaN,0.0,0.0,NaN,NaN,NaN,0.000000,NaN
zinnfr01,1865,1888,1,2,7,0,0,0,0,0,...,1,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.000000,NaN
zinngu01,9435,9565,5,314,1103,136,297,51,23,15,...,109,77.0,NaN,6.0,29.0,NaN,NaN,NaN,1.256326,NaN
zinnji01,9475,9611,5,76,120,17,34,6,2,2,...,7,18.0,NaN,1.0,3.0,NaN,NaN,NaN,1.113134,NaN
zinsebi01,1918,1944,1,2,0,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
zinteal01,3936,4006,2,67,78,7,13,4,0,3,...,5,34.0,0.0,0.0,0.0,1.0,0.0,84.0,0.342246,0.518717
zipfebu01,3876,3923,2,118,354,38,78,11,6,10,...,32,92.0,1.0,1.0,4.0,2.0,4.0,393.0,0.439130,0.660038
ziskri01,25337,25701,13,1453,5144,681,1477,245,26,207,...,533,910.0,52.0,12.0,7.0,41.0,138.0,5777.0,3.555915,5.325409
zitoba01,29670,30106,15,434,344,12,35,0,0,0,...,18,99.0,0.0,0.0,56.0,0.0,4.0,418.0,0.831232,3.169561
zitzmbi01,13265,13473,8,406,1004,197,268,38,11,3,...,83,85.0,NaN,16.0,39.0,NaN,NaN,NaN,1.497146,NaN
zmiched01,3768,3821,2,13,17,0,1,0,0,0,...,0,10.0,NaN,0.0,0.0,NaN,NaN,NaN,0.076923,NaN
zobribe01,23772,24136,13,1337,4840,735,1287,296,38,145,...,700,839.0,32.0,26.0,23.0,55.0,97.0,5650.0,3.075929,4.926333
zoccope01,1977,2003,1,20,37,0,4,1,0,0,...,2,13.0,0.0,0.0,0.0,0.0,1.0,39.0,0.108108,0.162162
zoldasa01,19180,19480,11,251,286,16,50,6,0,0,...,10,52.0,NaN,1.0,9.0,NaN,4.0,NaN,2.032409,NaN
zoskyed01,9840,9977,5,44,50,4,8,1,2,0,...,1,13.0,0.0,0.0,1.0,1.0,1.0,53.0,0.776720,1.099471
zuberbi01,22956,23307,13,224,229,10,31,4,5,0,...,10,66.0,NaN,0.0,20.0,NaN,8.0,NaN,1.632046,NaN
zuberjo01,3938,3994,2,68,136,13,34,7,1,3,...,12,20.0,1.0,1.0,1.0,1.0,4.0,151.0,0.497192,0.729426
zuletju01,3950,4001,2,79,174,24,43,11,0,9,...,10,51.0,1.0,6.0,0.0,1.0,5.0,186.0,0.511099,0.634850
zumayjo01,9920,10040,5,171,0,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
zuninmi01,7964,8058,4,350,1125,117,219,43,2,50,...,75,404.0,1.0,31.0,8.0,8.0,23.0,1217.0,0.794106,1.165318
zupcibo01,9830,9964,6,319,795,99,199,47,4,7,...,57,137.0,3.0,6.0,20.0,8.0,15.0,883.0,0.881314,1.297835
zupofr01,5817,5876,3,16,18,3,3,1,0,0,...,2,6.0,0.0,0.0,0.0,0.0,0.0,20.0,0.583333,0.916667
zuvelpa01,17622,17875,9,209,491,41,109,17,2,2,...,34,50.0,1.0,2.0,18.0,0.0,8.0,544.0,1.219067,2.196235
zuverge01,19240,19551,12,266,142,5,21,2,1,0,...,9,39.0,0.0,0.0,16.0,0.0,3.0,91.0,1.312695,inf
zwilldu01,7552,7655,4,366,1280,167,364,76,15,30,...,128,139.0,NaN,4.0,31.0,NaN,NaN,NaN,0.896112,NaN
zychto01,3980,4031,2,25,0,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [76]:
HR_600 = q4[q4.HR > 600].sort_values(by = 'HR', ascending = True)

In [77]:
HR_600 #List of players who are in the 600 HR Club

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,...,BB,SO,IBB,HBP,SH,SF,GIDP,PA,Avg,OBP
playerID,,,,,,,,,,,,,,,,,,,,,
sosasa01,37392,37945,20,2354,8813,1475,2408,379,45,609,...,929,2306.0,154.0,59.0,17.0,78.0,202.0,9991.0,5.094862,7.501895
thomeji01,49250,50065,28,2543,8422,1583,2328,451,26,612,...,1747,2548.0,173.0,69.0,1.0,74.0,165.0,10417.0,6.700664,11.920345
griffke02,45287,45997,24,2671,9801,1662,2781,524,38,630,...,1312,1779.0,246.0,81.0,8.0,102.0,199.0,11469.0,6.319576,10.221851
mayswi01,44413,45145,24,2992,10881,2062,3283,523,140,660,...,1464,1526.0,192.0,44.0,13.0,91.0,251.0,11338.0,6.667193,9.412565
rodrial01,43450,44101,22,2784,10566,2021,3115,548,31,696,...,1338,2287.0,97.0,176.0,16.0,111.0,261.0,12128.0,6.232222,9.341105
ruthba01,41690,42339,22,2503,8398,2174,2873,506,136,714,...,2062,1330.0,NaN,43.0,113.0,NaN,2.0,NaN,7.100518,NaN
aaronha01,44482,45195,23,3298,12364,2174,3771,624,98,755,...,1402,1383.0,293.0,32.0,21.0,121.0,328.0,13695.0,6.924731,10.029224
bondsba01,43208,43923,22,2986,9847,2227,2935,601,77,762,...,2558,1539.0,688.0,106.0,4.0,91.0,165.0,13188.0,6.562727,14.335937

## 5) How many players have hit 40 2Bs, 10 3Bs, 200 Hits, and 30 HRs (inclusive) in one season? (Number Only)

In [15]:
q5 = df[(df['2B']>=40) & (df['3B']>=10) & (df['H'] >= 200) & (df['HR'] >= 30)]

In [16]:
q5

,playerID,nameFirst,nameLast,birthYear,yearID,stint,teamID,lgID,G,AB,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
19039,ruthba01,Babe,Ruth,1895,1921,1,NYA,AL,152,540,...,171.0,17.0,13.0,145,81.0,NaN,4.0,4.0,NaN,NaN
19381,hornsro01,Rogers,Hornsby,1896,1922,1,SLN,NL,154,623,...,152.0,17.0,12.0,65,50.0,NaN,1.0,15.0,NaN,NaN
20096,ruthba01,Babe,Ruth,1895,1923,1,NYA,AL,152,522,...,131.0,17.0,21.0,170,93.0,NaN,4.0,3.0,NaN,NaN
21005,hornsro01,Rogers,Hornsby,1896,1925,1,SLN,NL,138,504,...,143.0,5.0,3.0,83,39.0,NaN,2.0,16.0,NaN,NaN
22019,gehrilo01,Lou,Gehrig,1903,1927,1,NYA,AL,155,584,...,175.0,10.0,8.0,109,84.0,NaN,3.0,21.0,NaN,NaN
23619,gehrilo01,Lou,Gehrig,1903,1930,1,NYA,AL,154,581,...,174.0,12.0,14.0,101,63.0,NaN,3.0,18.0,NaN,NaN
23672,hermaba01,Babe,Herman,1903,1930,1,BRO,NL,153,614,...,130.0,18.0,NaN,66,56.0,NaN,4.0,15.0,NaN,NaN
23886,simmoal01,Al,Simmons,1902,1930,1,PHA,AL,138,554,...,165.0,9.0,2.0,39,34.0,NaN,1.0,17.0,NaN,NaN
24750,kleinch01,Chuck,Klein,1904,1932,1,PHI,NL,154,650,...,137.0,20.0,NaN,60,49.0,NaN,1.0,0.0,NaN,NaN
25593,colliri02,Ripper,Collins,1904,1934,1,SLN,NL,154,600,...,128.0,2.0,NaN,57,50.0,NaN,2.0,3.0,NaN,11.0
26200,greenha01,Hank,Greenberg,1911,1935,1,DET,AL,152,619,...,170.0,4.0,3.0,87,91.0,NaN,0.0,4.0,NaN,NaN
27248,greenha01,Hank,Greenberg,1911,1937,1,DET,AL,154,594,...,183.0,8.0,3.0,102,101.0,NaN,3.0,2.0,NaN,NaN
27391,medwijo01,Joe,Medwick,1911,1937,1,SLN,NL,156,633,...,154.0,4.0,NaN,41,50.0,NaN,2.0,1.0,NaN,11.0
33671,musiast01,Stan,Musial,1920,1948,1,SLN,NL,155,611,...,131.0,7.0,NaN,79,34.0,NaN,3.0,1.0,NaN,18.0
34242,musiast01,Stan,Musial,1920,1949,1,SLN,NL,157,612,...,123.0,3.0,NaN,107,38.0,NaN,2.0,0.0,NaN,12.0
75776,garcino01,Nomar,Garciaparra,1973,1997,1,BOS,AL,153,684,...,98.0,22.0,9.0,35,92.0,2.0,6.0,2.0,7.0,9.0

In [21]:
q5['playerID'].nunique() # Unique number of players who have hit 40 2Bs, 10 3Bs, 200 Hits, and 30 HRs (inclusive) in one season

11

## 6)	How many players have had 100 or more SBs in a season? (Dataframe)

In [22]:
q6 = df.groupby(['playerID','yearID']).sum()

In [23]:
q6

                  birthYear  stint    G   AB    R    H  2B  3B  HR    RBI  \
playerID  yearID
aardsda01 2004         1981      1   11    0    0    0   0   0   0    0.0
          2006         1981      1   45    2    0    0   0   0   0    0.0
          2007         1981      1   25    0    0    0   0   0   0    0.0
          2008         1981      1   47    1    0    0   0   0   0    0.0
          2009         1981      1   73    0    0    0   0   0   0    0.0
          2010         1981      1   53    0    0    0   0   0   0    0.0
          2012         1981      1    1    0    0    0   0   0   0    0.0
          2013         1981      1   43    0    0    0   0   0   0    0.0
          2015         1981      1   33    1    0    0   0   0   0    0.0
aaronha01 1954         1934      1  122  468   58  131  27   6  13   69.0
          1955         1934      1  153  602  105  189  37   9  27  106.0
          1956         1934      1  153  609  106  200  34  14  26   92.0
          1957         1934      1  151  615  118  198  27   6  44  132.0
          1958         1934      1  153  601  109  196  34   4  30   95.0
          1959         1934      1  154  629  116  223  46   7  39  123.0
          1960         1934      1  153  590  102  172  20  11  40  126.0
          1961         1934      1  155  603  115  197  39  10  34  120.0
          1962         1934      1  156  592  127  191  28   6  45  128.0
          1963         1934      1  161  631  121  201  29   4  44  130.0
          1964         1934      1  145  570  103  187  30   2  24   95.0
          1965         1934      1  150  570  109  181  40   1  32   89.0
          1966         1934      1  158  603  117  168  23   1  44  127.0
          1967         1934      1  155  600  113  184  37   3  39  109.0
          1968         1934      1  160  606   84  174  33   4  29   86.0
          1969         1934      1  147  547  100  164  30   3  44   97.0
          1970         1934      1  150  516  103  154  26   1  38  118.0
          1971         1934      1  139  495   95  162  22   3  47  118.0
          1972         1934      1  129  449   75  119  10   0  34   77.0
          1973         1934      1  120  392   84  118  12   1  40   96.0
          1974         1934      1  112  340   47   91  16   0  20   69.0
...                     ...    ...  ...  ...  ...  ...  ..  ..  ..    ...
zupcibo01 1991         1966      1   18   25    3    4   0   0   1    3.0
          1992         1966      1  124  392   46  108  19   1   3   43.0
          1993         1966      1  141  286   40   69  24   2   2   26.0
          1994         3932      3   36   92   10   18   4   1   1    8.0
zupofr01  1957         1939      1   10   12    2    1   0   0   0    0.0
          1958         1939      1    1    2    0    0   0   0   0    0.0
          1961         1939      1    5    4    1    2   1   0   0    0.0
zuvelpa01 1982         1958      1    2    1    0    0   0   0   0    0.0
          1983         1958      1    3    5    0    0   0   0   0    0.0
          1984         1958      1   11   25    2    5   1   0   0    1.0
          1985         1958      1   81  190   16   48   8   1   0    4.0
          1986         1958      1   21   48    2    4   1   0   0    2.0
          1987         1958      1   14   34    2    6   0   0   0    0.0
          1988         1958      1   51  130    9   30   5   1   0    7.0
          1989         1958      1   24   58   10   16   2   0   2    6.0
          1991         1958      1    2    0    0    0   0   0   0    0.0
zuverge01 1951         1924      1   16    0    0    0   0   0   0    0.0
          1952         1924      1    2    0    1    0   0   0   0    0.0
          1954         3848      3   37   66    2    9   1   0   0    3.0
          1955         3848      3   42   27    1    5   1   0   0    0.0
          1956         1924      1   62   17    0    2   0   0   0    2.0
          1957         1924      1   56   23    1    3   0   0   0    0.0
          1958         1924      1   45    9    0    2   0   1   0    2.0
          1959         1924      1    6    0    0    0   0   0   0    0.0
zwilldu01 1910         1888      1   27   87    7   16   5   0   0    5.0
          1914         1888      1  154  592   91  185  38   8  16   95.0
          1915         1888      1  150  548   65  157  32   7  13   94.0
          1916         1888      1   35   53    4    6   1   0   1    8.0
zychto01  2015         1990      1   13    0    0    0   0   0   0    0.0
          2016         1990      1   12    0    0    0   0   0   0    0.0

                    SB    CS  BB    SO   IBB  HBP    SH    SF  GIDP
playerID  yearID
aardsda01 2004     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          2006     0.0   0.0   0   0.0   0.0  0.0   1.0   0.0   0.0
          2007     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          2008     0.0   0.0   0   1.0   0.0  0.0   0.0   0.0   0.0
          2009     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          2010     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          2012     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          2013     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          2015     0.0   0.0   0   1.0   0.0  0.0   0.0   0.0   0.0
aaronha01 1954     2.0   2.0  28  39.0   NaN  3.0   6.0   4.0  13.0
          1955     3.0   1.0  49  61.0   5.0  3.0   7.0   4.0  20.0
          1956     2.0   4.0  37  54.0   6.0  2.0   5.0   7.0  21.0
          1957     1.0   1.0  57  58.0  15.0  0.0   0.0   3.0  13.0
          1958     4.0   1.0  59  49.0  16.0  1.0   0.0   3.0  21.0
          1959     8.0   0.0  51  54.0  17.0  4.0   0.0   9.0  19.0
          1960    16.0   7.0  60  63.0  13.0  2.0   0.0  12.0   8.0
          1961    21.0   9.0  56  64.0  20.0  2.0   1.0   9.0  16.0
          1962    15.0   7.0  66  73.0  14.0  3.0   0.0   6.0  14.0
          1963    31.0   5.0  78  94.0  18.0  0.0   0.0   5.0  11.0
          1964    22.0   4.0  62  46.0   9.0  0.0   0.0   2.0  22.0
          1965    24.0   4.0  60  81.0  10.0  1.0   0.0   8.0  15.0
          1966    21.0   3.0  76  96.0  15.0  1.0   0.0   8.0  14.0
          1967    17.0   6.0  63  97.0  19.0  0.0   0.0   6.0  11.0
          1968    28.0   5.0  64  62.0  23.0  1.0   0.0   5.0  21.0
          1969     9.0  10.0  87  47.0  19.0  2.0   0.0   3.0  14.0
          1970     9.0   0.0  74  63.0  15.0  2.0   0.0   6.0  13.0
          1971     1.0   1.0  71  58.0  21.0  2.0   0.0   5.0   9.0
          1972     4.0   0.0  92  55.0  15.0  1.0   0.0   2.0  17.0
          1973     1.0   1.0  68  51.0  13.0  1.0   0.0   4.0   7.0
          1974     1.0   0.0  39  29.0   6.0  0.0   1.0   2.0   6.0
...                ...   ...  ..   ...   ...  ...   ...   ...   ...
zupcibo01 1991     0.0   0.0   1   6.0   0.0  0.0   1.0   0.0   0.0
          1992     2.0   2.0  25  60.0   1.0  4.0   7.0   4.0   6.0
          1993     5.0   2.0  27  54.0   2.0  2.0   8.0   3.0   7.0
          1994     0.0   1.0   4  17.0   0.0  0.0   4.0   1.0   2.0
zupofr01  1957     0.0   0.0   1   4.0   0.0  0.0   0.0   0.0   0.0
          1958     0.0   0.0   0   1.0   0.0  0.0   0.0   0.0   0.0
          1961     0.0   0.0   1   1.0   0.0  0.0   0.0   0.0   0.0
zuvelpa01 1982     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          1983     0.0   0.0   2   1.0   0.0  1.0   0.0   0.0   0.0
          1984     0.0   0.0   2   3.0   0.0  0.0   0.0   0.0   0.0
          1985     2.0   0.0  16  14.0   1.0  0.0   4.0   0.0   3.0
          1986     0.0   0.0   5   4.0   0.0  0.0   4.0   0.0   1.0
          1987     0.0   0.0   0   4.0   0.0  0.0   2.0   0.0   1.0
          1988     0.0   0.0   8  13.0   0.0  0.0   8.0   0.0   3.0
          1989     0.0   0.0   1  11.0   0.0  1.0   0.0   0.0   0.0
          1991     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
zuverge01 1951     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          1952     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          1954     0.0   1.0   1  15.0   NaN  0.0   9.0   0.0   2.0
          1955     0.0   0.0   1   7.0   0.0  0.0   1.0   0.0   1.0
          1956     0.0   0.0   1   7.0   0.0  0.0   4.0   0.0   0.0
          1957     0.0   0.0   3   8.0   0.0  0.0   2.0   0.0   0.0
          1958     0.0   0.0   1   2.0   0.0  0.0   0.0   0.0   0.0
          1959     0.0   0.0   2   0.0   0.0  0.0   0.0   0.0   0.0
zwilldu01 1910     1.0   NaN  11   NaN   NaN  1.0   1.0   NaN   NaN
          1914    21.0   NaN  46  68.0   NaN  1.0  10.0   NaN   NaN
          1915    24.0   NaN  67  65.0   NaN  2.0  18.0   NaN   NaN
          1916     0.0   NaN   4   6.0   NaN  0.0   2.0   NaN   NaN
zychto01  2015     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0
          2016     0.0   0.0   0   0.0   0.0  0.0   0.0   0.0   0.0

[95250 rows x 19 columns]

In [24]:
SB_100 = q6[q6.SB > 100].sort_values(by = 'SB', ascending = True)

In [26]:
SB_100 # Players who have had 100 or more SBs in a season

,,birthYear,stint,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
playerID,yearID,,,,,,,,,,,,,,,,,,,
hamilbi01,1890,1866,1,123,496,133,161,13,9,2,49.0,102.0,NaN,83,37.0,NaN,9.0,NaN,NaN,NaN
fogarji01,1887,1864,1,126,495,113,129,26,12,8,50.0,102.0,NaN,82,44.0,NaN,10.0,NaN,NaN,NaN
brownpe01,1887,1861,1,134,547,137,220,35,16,4,118.0,103.0,NaN,55,NaN,NaN,8.0,NaN,NaN,NaN
nicolhu01,1888,1858,1,135,548,112,131,10,2,1,35.0,103.0,NaN,67,NaN,NaN,7.0,NaN,NaN,NaN
willsma01,1962,1932,1,165,695,130,208,13,10,6,48.0,104.0,13.0,51,57.0,1.0,2.0,7.0,4.0,7.0
brownto01,1891,1860,1,137,589,177,189,30,21,5,72.0,106.0,NaN,70,96.0,NaN,4.0,NaN,NaN,NaN
colemvi01,1986,1961,1,154,600,94,139,13,8,0,29.0,107.0,14.0,60,98.0,0.0,2.0,3.0,5.0,4.0
henderi01,1983,1958,1,145,513,105,150,25,7,9,48.0,108.0,19.0,103,80.0,8.0,4.0,1.0,1.0,11.0
colemvi01,1987,1961,1,151,623,121,180,14,10,3,43.0,109.0,22.0,70,126.0,0.0,3.0,5.0,1.0,7.0
lathaar01,1888,1860,1,133,570,119,151,19,5,2,31.0,109.0,NaN,43,NaN,NaN,8.0,NaN,NaN,NaN
colemvi01,1985,1961,1,151,636,107,170,20,10,1,40.0,110.0,25.0,50,115.0,1.0,0.0,5.0,1.0,3.0
hamilbi01,1889,1866,1,137,534,144,161,17,12,3,77.0,111.0,NaN,87,41.0,NaN,14.0,NaN,NaN,NaN
wardjo01,1887,1860,1,129,545,114,184,16,5,1,53.0,111.0,NaN,29,12.0,NaN,4.0,NaN,NaN,NaN
hamilbi01,1891,1866,1,133,527,141,179,23,7,2,60.0,111.0,NaN,102,28.0,NaN,7.0,NaN,NaN,NaN
comisch01,1887,1859,1,125,538,139,180,22,5,4,103.0,117.0,NaN,27,NaN,NaN,7.0,NaN,NaN,NaN
brocklo01,1974,1939,1,153,635,105,194,25,7,3,48.0,118.0,33.0,61,88.0,16.0,2.0,2.0,1.0,8.0
lathaar01,1887,1860,1,136,627,163,198,35,10,2,83.0,129.0,NaN,45,NaN,NaN,5.0,NaN,NaN,NaN
henderi01,1982,1958,1,149,536,119,143,24,4,10,51.0,130.0,42.0,116,94.0,1.0,2.0,0.0,2.0,5.0
nicolhu01,1887,1858,1,125,475,122,102,18,2,1,34.0,138.0,NaN,86,NaN,NaN,5.0,NaN,NaN,NaN

## 7) How many players in the 1960s have hit more than 200 HRs? (Dataframe)

In [256]:
q7=df[df['yearID']==1960]

In [257]:
q7n = q7.groupby('playerID').agg({'HR':'sum'})

In [260]:
q7n.count() #575 players in 1960 who hit more than 200 HR's

HR    575
dtype: int64

## 8) Who has hit the most HRs in history? (Dataframe)

In [4]:
q8 = df.groupby('playerID').sum()

In [5]:
q8n = q8.sort_values(by = 'HR', ascending = False)

In [6]:
q8n.nlargest(5, 'HR')

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
playerID,,,,,,,,,,,,,,,,,,,,
bondsba01,43208,43923,22,2986,9847,2227,2935,601,77,762,1996.0,514.0,141.0,2558,1539.0,688.0,106.0,4.0,91.0,165.0
aaronha01,44482,45195,23,3298,12364,2174,3771,624,98,755,2297.0,240.0,73.0,1402,1383.0,293.0,32.0,21.0,121.0,328.0
ruthba01,41690,42339,22,2503,8398,2174,2873,506,136,714,2217.0,123.0,117.0,2062,1330.0,NaN,43.0,113.0,NaN,2.0
rodrial01,43450,44101,22,2784,10566,2021,3115,548,31,696,2086.0,329.0,76.0,1338,2287.0,97.0,176.0,16.0,111.0,261.0
mayswi01,44413,45145,24,2992,10881,2062,3283,523,140,660,1903.0,338.0,103.0,1464,1526.0,192.0,44.0,13.0,91.0,251.0

## 9) Who had the most hits in the 1970s? (Dataframe)

In [263]:
q9=df[df['yearID']==1970]

In [266]:
q9n = q9.groupby(['playerID','yearID']).agg({'H':'sum'})

In [267]:
q9n.nlargest(1, 'H')

                   H
playerID yearID
rosepe01 1970    205

## 10) Top 5 highest OBP (on base percentage) with at least 500 PAs in 1977?  (Dataframe)

In [18]:
bbE = df
bbE['PA'] = bbE['AB'] + bbE['BB'] + bbE['IBB'] + bbE['SH'] + bbE['SF']
bbE['Avg'] = bbE['H'] / bbE['AB']
bbE['OBP'] = (bbE['H'] + bbE['BB'] + bbE['IBB'] + bbE['SH'] + bbE['SF'])/ bbE['AB']

In [9]:
q10= bbE[bbE['yearID'] == 1977]

In [10]:
q10n = q10.groupby('playerID').sum()

In [11]:
q10nn = q10n[q10n['PA'] >= 500]

In [19]:
q10nn.nlargest(5,'OBP')

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,...,BB,SO,IBB,HBP,SH,SF,GIDP,PA,Avg,OBP
playerID,,,,,,,,,,,,,,,,,,,,,
raderdo02,3888,3954,3,148,483,66,121,26,5,18,...,71,105.0,3.0,4.0,5.0,5.0,16.0,567.0,0.510205,0.872637
bochtbr01,3900,3954,3,137,492,64,148,23,1,7,...,47,42.0,3.0,0.0,8.0,5.0,20.0,555.0,0.593571,0.813878
hortowi01,3884,3954,3,140,523,55,151,23,3,15,...,42,117.0,5.0,0.0,0.0,8.0,15.0,578.0,0.539017,0.644990
singlke01,1947,1977,1,152,536,90,176,24,0,24,...,107,101.0,13.0,2.0,0.0,6.0,15.0,662.0,0.328358,0.563433
smithre06,1945,1977,1,148,488,104,150,27,4,32,...,104,76.0,11.0,3.0,1.0,7.0,5.0,611.0,0.307377,0.559426

## 11) Top 8 highest averages in 2013 with at least 300 PAs? (Dataframe)

In [13]:
q11 = df[(df['yearID'] == 2013)]

In [14]:
q11n = q11.groupby('playerID').sum()

In [15]:
q11nn = q11n[q11n['PA'] >= 300].sort_values(by = 'Avg', ascending = False)

In [16]:
q11nn.nlargest(8, 'Avg')

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,...,BB,SO,IBB,HBP,SH,SF,GIDP,PA,Avg,OBP
playerID,,,,,,,,,,,,,,,,,,,,,
byrdma01,3954,4026,3,147,532,75,155,35,5,24,...,31,144.0,2.0,8.0,1.0,7.0,11.0,573.0,0.602463,0.747883
iglesjo01,3980,4026,3,109,350,39,106,16,2,3,...,15,60.0,0.0,11.0,4.0,2.0,7.0,371.0,0.589492,0.709216
youngmi02,3952,4026,3,147,519,52,145,26,5,8,...,43,83.0,4.0,1.0,0.0,2.0,21.0,568.0,0.589367,0.729010
riosal01,3962,4026,3,156,616,83,171,33,4,18,...,41,108.0,2.0,2.0,0.0,2.0,17.0,661.0,0.556314,0.691473
buckjo01,3960,4026,3,110,392,39,87,11,0,15,...,29,104.0,4.0,8.0,0.0,2.0,13.0,427.0,0.548007,0.643116
suzukku01,3966,4026,3,94,285,25,66,13,1,5,...,22,35.0,6.0,3.0,2.0,4.0,2.0,319.0,0.525253,0.712843
callaal01,3966,4026,3,136,453,52,117,20,0,10,...,53,47.0,2.0,1.0,3.0,6.0,12.0,517.0,0.522141,0.797587
youngde03,3970,4026,3,103,334,30,87,16,0,11,...,20,78.0,0.0,4.0,0.0,3.0,8.0,357.0,0.519094,0.690821

## 12) Leaders in hits from 1940 up to and including 1949. (Dataframe)

In [23]:
num_years = np.linspace(1940, 1949,10).astype(np.int64)
df3 = pd.read_csv('Batting.csv')
df_leaders = {}
count = 0
for i in num_years:
    y = df3[df3['yearID'] == i].groupby('playerID').sum().nlargest(1, 'H')
    df_leaders[count] = pd.DataFrame(y)
    count = count + 1
value = pd.concat(df_leaders)
value

,,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
,playerID,,,,,,,,,,,,,,,,,,,,
0,cramedo01,1905,1940,1,150,661,94,200,27,12,1,51.0,3.0,5.0,36,29.0,NaN,1.0,14.0,NaN,13.0
1,travice01,1913,1941,1,152,608,106,218,39,19,7,101.0,2.0,2.0,52,25.0,NaN,1.0,2.0,NaN,13.0
2,peskyjo01,1919,1942,1,147,620,105,205,29,9,2,51.0,12.0,7.0,42,36.0,NaN,2.0,22.0,NaN,8.0
3,musiast01,1920,1943,1,157,617,108,220,48,20,13,81.0,9.0,NaN,72,18.0,NaN,2.0,10.0,NaN,17.0
4,stirnsn01,1918,1944,1,154,643,125,205,35,16,8,43.0,55.0,11.0,73,87.0,NaN,1.0,6.0,NaN,6.0
5,holmeto01,1917,1945,1,154,636,125,224,47,6,28,117.0,15.0,NaN,70,9.0,NaN,4.0,3.0,NaN,11.0
6,musiast01,1920,1946,1,156,624,124,228,50,20,16,103.0,7.0,NaN,73,31.0,NaN,3.0,2.0,NaN,7.0
7,peskyjo01,1919,1947,1,155,638,106,207,27,8,0,39.0,12.0,9.0,72,22.0,NaN,0.0,9.0,NaN,10.0
8,musiast01,1920,1948,1,155,611,135,230,46,18,39,131.0,7.0,NaN,79,34.0,NaN,3.0,1.0,NaN,18.0
9,musiast01,1920,1949,1,157,612,128,207,41,13,36,123.0,3.0,NaN,107,38.0,NaN,2.0,0.0,NaN,12.0

## 13) Who led MLB with the most hits the most times?  And how many times?  (Dataframe, Number)

## 14) Which players have played the most games for their careers?  Top 5, descending by games played presented as a dataframe

In [24]:
q14 = df.groupby('playerID').sum()

In [25]:
q14n = q14.nlargest(5, 'G')

In [26]:
q14n

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,...,BB,SO,IBB,HBP,SH,SF,GIDP,PA,Avg,OBP
playerID,,,,,,,,,,,,,,,,,,,,,
rosepe01,48525,49372,26,3562,14053,2165,4256,746,135,160,...,1566,1143.0,167.0,107.0,56.0,79.0,247.0,15921.0,7.516937,10.843925
yastrca01,44597,45356,23,3308,11988,1816,3419,646,59,452,...,1845,1393.0,190.0,40.0,13.0,105.0,323.0,14141.0,6.527357,10.655509
aaronha01,44482,45195,23,3298,12364,2174,3771,624,98,755,...,1402,1383.0,293.0,32.0,21.0,121.0,328.0,13695.0,6.924731,10.029224
henderi01,56782,57754,33,3081,10961,2295,3055,510,66,297,...,2190,1694.0,61.0,98.0,30.0,67.0,172.0,13309.0,7.803474,14.146079
cobbty01,45264,45996,24,3035,11434,2246,4189,724,295,117,...,1249,357.0,NaN,94.0,295.0,NaN,NaN,NaN,8.665088,NaN

## 15) How many players have had more than 3000 hits for their careers while also hitting 500 or more HRs?  Just a number is okay here

In [52]:
q15 = df.groupby('playerID').sum()

In [53]:
q15n=q15[(q15['H']>=3000) & (q15['HR']>=500)]

In [58]:
q15n['stint'].nunique()

5

## 16) How many HRs were hit during the entire 1988 season?  Just a number is okay here

In [59]:
q16 = df[df.yearID == 1988].groupby('yearID').sum()

In [61]:
q16['HR']

yearID
1988    3180
Name: HR, dtype: int64

## 17) Please filter out and show me the top 3 average seasons by Wade Boggs during his career in seasons in which he had at least 500 ABs.  I would like a dataframe sorted by average

In [85]:
q17 = df[(df['nameFirst'] == 'Wade') & (df['nameLast'] == 'Boggs')]

In [66]:
q17n = q17.groupby('yearID').agg({'Avg': 'mean', 'AB': 'sum'})

In [68]:
q17nn = q17n[q17n['AB'] >= 500].nlargest(3, 'Avg')

In [69]:
q17nn

             Avg   AB
yearID
1985    0.367534  653
1988    0.366438  584
1987    0.362976  551

## 18) Please filter out the top OBPs for the 1995 season with at least 400 PAs, sorted by OBP.  I would like a dataframe for this

In [91]:
q18 = bbE[bbE['yearID']==1995]

In [92]:
q18n=q18.groupby('playerID').sum()

In [93]:
q18nn = q18n[q18n['PA']>=400]

In [94]:
q18nn.nlargest(10, 'OBP')

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,...,BB,SO,IBB,HBP,SH,SF,GIDP,PA,Avg,OBP
playerID,,,,,,,,,,,,,,,,,,,,,
seguida01,3932,3990,3,130,456,68,141,25,4,12,...,40,47.0,5.0,3.0,8.0,3.0,10.0,512.0,0.634250,0.991130
butlebr01,3914,3990,3,129,513,78,154,18,9,1,...,67,51.0,2.0,0.0,10.0,6.0,5.0,598.0,0.584599,0.948192
bonilbo01,3926,3990,3,141,554,96,182,37,8,28,...,54,79.0,10.0,2.0,0.0,4.0,22.0,622.0,0.658254,0.899386
gonzalu01,3934,3990,3,133,471,69,130,29,8,13,...,57,63.0,8.0,6.0,1.0,6.0,16.0,543.0,0.548450,0.847456
sierrru01,3930,3990,3,126,479,73,126,32,0,19,...,46,76.0,4.0,0.0,0.0,8.0,8.0,537.0,0.525617,0.770349
colemvi01,3922,3990,3,115,455,66,131,23,6,5,...,37,80.0,2.0,2.0,5.0,1.0,8.0,500.0,0.576813,0.769035
zeileto01,3930,3990,3,113,426,50,105,22,0,14,...,34,76.0,1.0,4.0,4.0,5.0,13.0,470.0,0.518763,0.761041
lewisda01,3934,3990,3,132,472,66,118,13,3,1,...,34,57.0,0.0,8.0,12.0,1.0,9.0,519.0,0.497826,0.713701
kellyro01,3928,3990,3,136,504,58,140,23,2,7,...,22,79.0,6.0,6.0,0.0,7.0,14.0,539.0,0.552413,0.702638
devermi01,3926,3990,3,121,388,55,116,24,1,11,...,27,62.0,3.0,0.0,0.0,3.0,11.0,421.0,0.560852,0.690308

## 19) Who had the most 3Bs (in total) in 1922, 1925, 1926, and 1928?  I would like a dataframe with just the leader

In [95]:
q19 = df[(df['yearID'] == 1922) | (df['yearID'] == 1925) | (df['yearID'] == 1926) | (df['yearID'] == 1928)]

In [96]:
q19n = q19.groupby('playerID').sum()

In [97]:
q19n.nlargest(1, '3B')

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
playerID,,,,,,,,,,,,,,,,,,,,
walkecu01,7584,7701,4,571,2088,335,652,97,59,30,311.0,47.0,15.0,222,122.0,NaN,5.0,81.0,NaN,NaN

## 20) How many players have hit 30 or more HRs in season while also stealing (SB) 30 more or bases?  A number is okay here

In [157]:
q20 = df.groupby(['playerID']).agg({'HR':'sum','SB':'sum'})

In [160]:
q20n = q20[(q20['HR'] >= 30) & (q20['SB']>=30)]

In [164]:
q20n.shape[0]

1248

## 21) Who had the highest OBP is 1986 with at least 400 PAs? (Dataframe)

In [166]:
q21 = bbE[bbE['yearID'] == 1986].groupby('playerID').sum()

In [168]:
q21n = q21[q21['PA']>=400]

In [169]:
q21n.nlargest(1, 'OBP')

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,...,BB,SO,IBB,HBP,SH,SF,GIDP,PA,Avg,OBP
playerID,,,,,,,,,,,,,,,,,,,,,
bonilbo01,3926,3972,3,138,426,55,109,16,4,3,...,62,88.0,3.0,2.0,5.0,1.0,9.0,497.0,0.508814,0.843082

## 22) Same question but for 1997 and only in the NL (check league ID)? (Dataframe)

In [170]:
q22 = bbE[(bbE['yearID'] == 1997) & (bbE['lgID'] == 'NL')].groupby('playerID').sum()

In [171]:
q22n = q22[q22['PA']>=400]

In [172]:
q22n.nlargest(1, 'OBP')

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,...,BB,SO,IBB,HBP,SH,SF,GIDP,PA,Avg,OBP
playerID,,,,,,,,,,,,,,,,,,,,,
daultda01,3924,3994,3,136,395,68,104,21,8,14,...,76,74.0,5.0,2.0,0.0,9.0,4.0,485.0,0.525845,0.965894

## 23) Who had more than the league average HRs in 2012 (filter out all players with less 500 PAs)? (Dataframe)

In [177]:
q23 = bbE[bbE['yearID'] == 2012]

In [178]:
q23n = q23.groupby('playerID').sum()

In [179]:
q23nn = q23n[q23n['HR'] > q23n['HR'].mean()].sort_values(by = 'HR', ascending = False)

In [180]:
q23nn = q23nn[q23nn['PA'] >= 500]

In [181]:
q23nn

,birthYear,yearID,stint,G,AB,R,H,2B,3B,HR,...,BB,SO,IBB,HBP,SH,SF,GIDP,PA,Avg,OBP
playerID,,,,,,,,,,,,,,,,,,,,,
cabremi01,1983,2012,1,161,622,109,205,40,0,44,...,66,98.0,17.0,3.0,0.0,6.0,28.0,711.0,0.329582,0.472669
hamiljo03,1981,2012,1,148,562,103,160,31,2,43,...,60,162.0,13.0,5.0,0.0,9.0,9.0,644.0,0.284698,0.430605
grandcu01,1981,2012,1,160,596,102,138,18,4,43,...,75,195.0,4.0,5.0,1.0,7.0,5.0,683.0,0.231544,0.377517
encared01,1983,2012,1,151,542,93,152,24,0,42,...,84,94.0,12.0,11.0,0.0,7.0,6.0,645.0,0.280443,0.470480
braunry02,1983,2012,1,154,598,108,191,36,3,41,...,63,128.0,15.0,11.0,0.0,5.0,12.0,681.0,0.319398,0.458194
dunnad01,1979,2012,1,151,539,87,110,19,0,41,...,105,222.0,3.0,1.0,0.0,4.0,8.0,651.0,0.204082,0.411874
stantmi03,1989,2012,1,123,449,75,130,30,1,37,...,46,143.0,9.0,5.0,0.0,1.0,5.0,505.0,0.289532,0.414254
beltrad01,1979,2012,1,156,604,95,194,33,2,36,...,36,82.0,8.0,5.0,0.0,9.0,8.0,657.0,0.321192,0.408940
willijo03,1979,2012,1,145,519,85,135,30,1,35,...,76,141.0,4.0,14.0,0.0,6.0,15.0,605.0,0.260116,0.425819
bruceja01,1987,2012,1,155,560,89,141,35,5,34,...,62,155.0,11.0,4.0,0.0,7.0,5.0,640.0,0.251786,0.394643
davisch02,1986,2012,1,139,515,75,139,20,0,33,...,37,169.0,6.0,7.0,0.0,3.0,8.0,561.0,0.269903,0.359223
canoro01,1982,2012,1,161,627,105,196,48,1,33,...,61,96.0,10.0,7.0,0.0,2.0,22.0,700.0,0.312600,0.429027
larocad01,1979,2012,1,154,571,76,155,35,1,33,...,67,138.0,7.0,0.0,0.0,9.0,10.0,654.0,0.271454,0.416813
jonesad01,1985,2012,1,162,648,103,186,39,3,32,...,34,126.0,0.0,13.0,0.0,2.0,15.0,684.0,0.287037,0.342593
reddijo01,1987,2012,1,156,611,85,148,29,5,32,...,55,151.0,8.0,2.0,1.0,4.0,15.0,679.0,0.242226,0.353519
beltrca01,1977,2012,1,151,547,83,147,26,1,32,...,65,124.0,15.0,2.0,1.0,4.0,9.0,632.0,0.268739,0.424132
davisik02,1987,2012,1,156,519,66,118,26,0,32,...,61,141.0,3.0,1.0,0.0,3.0,10.0,586.0,0.227360,0.356455
soriaal01,1976,2012,1,151,561,68,147,33,2,32,...,44,153.0,5.0,7.0,0.0,3.0,18.0,613.0,0.262032,0.354724
trumbma01,1986,2012,1,144,544,66,146,19,3,32,...,36,153.0,3.0,4.0,0.0,2.0,12.0,585.0,0.268382,0.343750
headlch01,1984,2012,1,161,604,95,173,31,2,31,...,86,157.0,2.0,4.0,0.0,5.0,7.0,697.0,0.286424,0.440397
mccutan01,1986,2012,1,157,593,107,194,29,6,31,...,70,132.0,13.0,5.0,0.0,5.0,9.0,681.0,0.327150,0.475548
kubelja01,1982,2012,1,141,506,75,128,30,4,30,...,57,151.0,7.0,2.0,0.0,6.0,11.0,576.0,0.252964,0.391304
troutmi01,1991,2012,1,139,559,129,182,27,8,30,...,67,139.0,4.0,6.0,0.0,7.0,7.0,637.0,0.325581,0.465116
hartco01,1982,2012,1,149,562,91,152,35,4,30,...,44,151.0,5.0,11.0,2.0,3.0,13.0,616.0,0.270463,0.366548
fieldpr01,1984,2012,1,162,581,83,182,33,1,30,...,85,84.0,18.0,17.0,0.0,7.0,19.0,691.0,0.313253,0.502582
pujolal01,1980,2012,1,154,607,85,173,50,0,30,...,52,76.0,16.0,5.0,0.0,6.0,19.0,681.0,0.285008,0.406919
alvarpe01,1987,2012,1,149,525,64,128,25,1,30,...,57,180.0,6.0,1.0,0.0,3.0,10.0,591.0,0.243810,0.369524
butlebi03,1986,2012,1,161,614,72,192,32,1,29,...,54,111.0,9.0,7.0,0.0,4.0,20.0,681.0,0.312704,0.421824
uptonbj01,1984,2012,1,146,573,79,141,29,3,28,...,45,169.0,0.0,1.0,4.0,8.0,13.0,630.0,0.246073,0.345550
hollima01,1980,2012,1,157,599,95,177,36,2,27,...,75,132.0,3.0,9.0,0.0,5.0,16.0,682.0,0.295492,0.434057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cabreme01,1984,2012,1,113,459,84,159,25,10,11,...,36,63.0,4.0,0.0,1.0,5.0,8.0,505.0,0.346405,0.446623
reyesjo01,1983,2012,1,160,642,86,184,37,12,11,...,63,56.0,9.0,0.0,5.0,6.0,10.0,725.0,0.286604,0.415888
crispco01,1979,2012,1,120,455,68,118,25,7,11,...,45,64.0,0.0,0.0,6.0,2.0,9.0,508.0,0.259341,0.375824
lawribr01,1990,2012,1,125,494,73,135,26,3,11,...,33,86.0,0.0,5.0,2.0,2.0,9.0,531.0,0.273279,0.348178
callaal01,1983,2012,1,138,457,55,115,20,0,10,...,56,59.0,1.0,0.0,3.0,4.0,6.0,521.0,0.251641,0.391685
mauerjo01,1983,2012,1,147,545,81,174,31,4,10,...,90,88.0,10.0,2.0,1.0,3.0,23.0,649.0,0.319266,0.510092
aokino01,1982,2012,1,151,520,81,150,37,4,10,...,43,55.0,1.0,13.0,7.0,5.0,6.0,576.0,0.288462,0.396154
pradoma01,1983,2012,1,156,617,81,186,42,6,10,...,58,69.0,2.0,2.0,4.0,9.0,19.0,690.0,0.301459,0.419773
dejesda01,1979,2012,1,148,506,76,133,28,8,9,...,61,89.0,1.0,9.0,2.0,4.0,9.0,574.0,0.262846,0.397233
bournmi01,1982,2012,1,155,624,96,171,26,10,9,...,70,155.0,1.0,3.0,2.0,4.0,2.0,701.0,0.274038,0.397436
deazaal01,1984,2012,1,131,524,81,147,29,6,9,...,47,109.0,3.0,9.0,4.0,1.0,1.0,579.0,0.280534,0.385496
alonsyo01,1987,2012,1,155,549,47,150,39,0,9,...,62,101.0,9.0,3.0,1.0,4.0,14.0,625.0,0.273224,0.411658
ramiral03,1981,2012,1,158,593,59,157,24,4,9,...,16,77.0,2.0,4.0,4.0,4.0,15.0,619.0,0.264755,0.308600
suzukic01,3946,4024,3,162,629,77,178,28,6,9,...,22,61.0,5.0,2.0,5.0,5.0,12.0,666.0,0.582780,0.697832
escobyu01,1982,2012,1,145,558,58,141,22,1,9,...,35,70.0,1.0,4.0,7.0,4.0,21.0,605.0,0.252688,0.336918
leeca01,3952,4024,3,147,550,53,145,27,1,9,...,58,49.0,4.0,1.0,0.0,6.0,13.0,618.0,0.529972,0.772327
youngmi02,1976,2012,1,156,611,79,169,27,3,8,...,33,70.0,3.0,1.0,0.0,6.0,26.0,653.0,0.276596,0.345336
aybarer01,1984,2012,1,141,517,67,150,31,5,8,...,22,61.0,1.0,5.0,7.0,2.0,11.0,549.0,0.290135,0.352031
kendrho01,1983,2012,1,147,550,57,158,32,3,8,...,29,115.0,1.0,4.0,6.0,5.0,26.0,591.0,0.287273,0.361818
paganan01,1981,2012,1,154,605,95,174,38,15,8,...,48,97.0,5.0,0.0,2.0,4.0,6.0,664.0,0.287603,0.385124
maybica01,1987,2012,1,147,507,67,123,20,5,8,...,44,110.0,1.0,4.0,3.0,3.0,12.0,558.0,0.242604,0.343195
scutama01,3950,4024,3,156,620,87,190,32,4,7,...,40,49.0,0.0,4.0,10.0,9.0,12.0,679.0,0.632697,0.825763
altuvjo01,1990,2012,1,147,576,80,167,34,4,7,...,40,74.0,0.0,6.0,4.0,4.0,8.0,624.0,0.289931,0.373264
barneda01,1985,2012,1,156,548,73,139,26,4,7,...,33,58.0,1.0,3.0,3.0,1.0,11.0,586.0,0.253650,0.322993
brantmi02,1987,2012,1,149,552,63,159,37,4,6,...,53,56.0,12.0,0.0,0.0,4.0,7.0,621.0,0.288043,0.413043
murphda08,1985,2012,1,156,571,62,166,40,3,6,...,36,82.0,5.0,1.0,0.0,4.0,12.0,616.0,0.290718,0.369527
pachejo01,1986,2012,1,132,475,51,147,32,3,5,...,22,61.0,2.0,3.0,1.0,4.0,13.0,504.0,0.309474,0.370526
escobal02,1986,2012,1,155,605,68,177,30,7,5,...,27,100.0,2.0,8.0,8.0,0.0,14.0,642.0,0.292562,0.353719
furcara01,1977,2012,1,121,477,69,126,18,3,5,...,44,57.0,1.0,1.0,5.0,4.0,7.0,531.0,0.264151,0.377358
spande01,1984,2012,1,128,516,71,146,38,4,4,...,47,62.0,0.0,0.0,4.0,1.0,10.0,568.0,0.282946,0.383721

## 24) Who is the youngest player to hit 50 or more HRs in a single season? (Dataframe)

## 25) Who are the five youngest players to hit 300 or more HRs for their career? (Dataframe)